# ========================================================================================
# Use ggtree package to annotate my food tree (if possible).
# Version 1
# Created on 02/23/2022 by Rie Sadohara
# ========================================================================================

# ========================================================================================
# Load data.
# ========================================================================================
  # setwd("E:/MSU OneDrive 20210829/PIC Cassoulet/PIC/By country")
  setwd("E:/MSU OneDrive 20210829/UMinn/Food_Tree-master/R")

  library(ggtree)
# Load your nwk data generated by TASSEL.
  # tree <- read.tree("TASSEL_NJ/NJTree_PIC_pl_geno999_by_country_het25_mi80_maf3.nwk")

#### **** ADD a semicolon at the end of your tree file content, and ####
#### CHANGE/or ADD the extension .nwk at the end of your file name. ####
  # mytree <- system.file("output/VVKAJ.reduced_2Lv.tree.nwk", package = "ggtree")
  # mytree

  tree <- read.tree("output/VVKAJ.reduced_2Lv.tree.nwk")
  tree
  
  # Use ggplot
  ggplot(tree, aes(x, y) ) + 
    geom_tree() + 
    theme_tree() +
    geom_tiplab()

  # Use ggtree
  ggtree(tree, ladderize = F) + # disable ladderizing (sorting by ggtree, CRITICAL!!!)
    geom_tiplab()
  
  # Plot a circular tree.
  VVKAJtree <- ggtree(tree, ladderize = F, layout = 'circular') +
    geom_tiplab()
  VVKAJtree
  
  # Save the tree with the food names.
  ggsave("VVKAJ_2Lv_10x10_tip.tif", VVKAJtree, width=10, height=10, device='tiff', dpi=150)
  
  # Show the node numbers 
  ggtree(tree, ladderize = F, layout = 'circular') +
    geom_text(aes(label=node), hjust= -0.1) 
  
  # Do some preparation to highlight and annotate
  tiplabels <- tree[["tip.label"]]
  length(tiplabels)  # 134 food items = tips for VVKAJ.
  
  # Make the nodes (root, L1s and L2s and so on) into a dataframe.   
    nodelabels <- tree[["node.label"]]
    length(nodelabels) # 42 = 1 root + 41 L1s&L2s.
    nodelabelsdf <- data.frame(nodelabels= nodelabels, 
                                  level= substr(nodelabels, 1,2), 
                                  seqnum=  seq(1:length(nodelabels)),  
                                  nodenum= seq(1:length(nodelabels))+length(tiplabels)  # This corresponds to the node numbers in the plot.
    )
    
    # Check everything's good.
    head(nodelabelsdf, 10)
    tail(nodelabelsdf, 10)
    
    # Replace 'fo' to 'root'
    nodelabelsdf[1, 2] <- 'root'
    
  # Take only the rows that are L1 and find their nodenumbers in order to annotate nodes.
  L1s <- subset(nodelabelsdf, level=='L1')  
  # This should have 9 rows.
  # if for some reason there are not 9, need to decrease the number of colors specified below. 
  
  # Add 9 colors for each L1 for plotting. 
  L1s$colors <- c('firebrick', 'pink', 'orange', 'gold', 'lightgreen', 
                  'seagreen', 'lightblue', 'royalblue', 'purple') 
  L1s
  
  # Make vectors for plotting.
  L1nodenum <- L1s$nodenum
  L1nodelabels <- L1s$nodelabels
  L1nodecolors <- L1s$colors 
  
  # highlight and annotate L1s using the nodenumbers. 
  VVKAJ_ann_hili <- ggtree(tree, ladderize = F, layout = 'circular') +
    # geom_text(aes(label=node), hjust= -0.3) +
    geom_hilight(   node=L1nodenum[1],  fill=L1nodecolors[1]) +
    geom_cladelabel(node=L1nodenum[1], color=L1nodecolors[1], label=L1nodelabels[1], offset=0.8, align=F) + 
    geom_hilight(   node=L1nodenum[2],  fill=L1nodecolors[2]) +
    geom_cladelabel(node=L1nodenum[2], color=L1nodecolors[2], label=L1nodelabels[2], offset=0.8, align=F) + 
    geom_hilight(   node=L1nodenum[3],  fill=L1nodecolors[3]) +
    geom_cladelabel(node=L1nodenum[3], color=L1nodecolors[3], label=L1nodelabels[3], offset=0.8, align=F) +  
    geom_hilight(   node=L1nodenum[4],  fill=L1nodecolors[4]) +
    geom_cladelabel(node=L1nodenum[4], color=L1nodecolors[4], label=L1nodelabels[4], offset=0.8, align=F) + 
    geom_hilight(   node=L1nodenum[5],  fill=L1nodecolors[5]) +
    geom_cladelabel(node=L1nodenum[5], color=L1nodecolors[5], label=L1nodelabels[5], offset=0.8, align=F) + 
    geom_hilight(   node=L1nodenum[6],  fill=L1nodecolors[6]) +
    geom_cladelabel(node=L1nodenum[6], color=L1nodecolors[6], label=L1nodelabels[6], offset=0.8, align=F) +
    geom_hilight(   node=L1nodenum[7],  fill=L1nodecolors[7]) +
    geom_cladelabel(node=L1nodenum[7], color=L1nodecolors[7], label=L1nodelabels[7], offset=0.8, align=F) + 
    geom_hilight(   node=L1nodenum[8],  fill=L1nodecolors[8]) +
    geom_cladelabel(node=L1nodenum[8], color=L1nodecolors[8], label=L1nodelabels[8], offset=0.8, align=F) + 
    geom_hilight(   node=L1nodenum[9],  fill=L1nodecolors[9]) +
    geom_cladelabel(node=L1nodenum[9], color=L1nodecolors[9], label=L1nodelabels[9], offset=0.8, align=F)   
    
  # Need to make the annotations darker and shorter, but great!!
  
    # Save the tree with the food names.
    ggsave("VVKAJ_ann_hili.tif", VVKAJ_ann_hili, width=10, height=10, device='tiff', dpi=150)
  
  
 
# ---------------------------------------------------------------------------------------------------------------

 # Example
  set.seed(2017-02-16)
  tree <- rtree(50)
  ggtree(tree)
  
  treetext = "(((ADH2:0.1[&&NHX:S=human], ADH1:0.11[&&NHX:S=human]):
  0.05 [&&NHX:S=primates:D=Y:B=100],ADHY:
  0.1[&&NHX:S=nematode],ADHX:0.12 [&&NHX:S=insect]):
  0.1[&&NHX:S=metazoa:D=N],(ADH4:0.09[&&NHX:S=yeast],
  ADH3:0.13[&&NHX:S=yeast], ADH2:0.12[&&NHX:S=yeast],
  ADH1:0.11[&&NHX:S=yeast]):0.1[&&NHX:S=Fungi])[&&NHX:D=N];"
  
  tree <- read.tree(textConnection(treetext))

  ggtree(tree) + geom_tiplab() + 
    geom_label(aes(x=branch, label='S'), fill='lightgreen') + 
    geom_label(aes(label="D"), fill='steelblue') + 
    geom_text(aes(label='B'), hjust=-.5)
  

# ---------------------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------------
  
