# ========================================================================================
# Use ggtree package to annotate my food tree (if possible).
# Version 1
# Created on 02/23/2022 by Rie Sadohara
# ========================================================================================

# ========================================================================================
# Load data.
# ========================================================================================
  # setwd("E:/MSU OneDrive 20210829/PIC Cassoulet/PIC/By country")
  setwd("E:/MSU OneDrive 20210829/UMinn/Food_Tree-master/R")

  library(ggtree)
# Load your nwk data generated by TASSEL.
#### **** ADD a semicolon at the end of your tree file content, and ####
#### CHANGE/or ADD the extension .nwk at the end of your file name. ####

  # VVKAJ
  tree <- read.tree("output/VVKAJ.reduced_2Lv.tree.nwk")
  tree

  # dietstudy (MCT)
  tree <- read.tree("output/mct.reduced_2Lv.tree.nwk")
  tree <- read.tree("output/mct.reduced_4Lv.tree.nwk")
  tree
 
  # Use ggplot - horizontal
  ggplot(tree, ladderize = F, aes(x, y) ) + # disable ladderizing (sorting nodes by ggtree, CRITICAL!!!)
    geom_tree() + 
    theme_tree() +
    geom_tiplab()

  # Use ggtree
  ggtree(tree, ladderize = F, layout = 'radial') + # disable ladderizing (sorting by ggtree, CRITICAL!!!)
    geom_tiplab()
  
  # Plot a circular tree. - hard to see with lots of samples
  VVKAJtree <- ggtree(tree, ladderize = F, layout = 'circular') +
    geom_tiplab()
  VVKAJtree
  
  # Save the tree with the food names.
  ggsave("VVKAJ_2Lv_10x10_tip.tif", VVKAJtree, width=10, height=10, device='tiff', dpi=150)
  
  # Show the node numbers 
  ggtree(tree, ladderize = F, layout = 'circular') +
    geom_text(aes(label=node), hjust= -0.1) 

# ---------------------------------------------------------------------------------------------------------------
# Do some preparation to highlight and annotate.
  # Save the tip labels as a vector for processing.
  tiplabels <- tree[["tip.label"]]
  length(tiplabels)  # 134 food items = tips for VVKAJ.
  
  # Make the nodes (root, L1s and L2s and so on) into a dataframe.   
    nodelabels <- tree[["node.label"]]
    length(nodelabels) # 42 = 1 root + 41 L1s&L2s.
    nodelabelsdf <- data.frame(nodelabels= nodelabels, 
                                    level= substr(nodelabels, 1,2), # Take the 1st and 2nd characters from nodelabels. 
                                   seqnum= seq(1:length(nodelabels)),   
                                  nodenum= seq(1:length(nodelabels))+length(tiplabels)  # This corresponds to the node numbers in the plot.
    )
    head(nodelabelsdf,20)
    # Replace 'fo' to 'root'
    nodelabelsdf[1, 2] <- 'root'
    
    # Ensure everything's good.
    head(nodelabelsdf, 20)
    tail(nodelabelsdf, 20)
    
  # Take only the rows that are L1 and find their nodenumbers in order to annotate nodes.
  L1s <- subset(nodelabelsdf, level=='L1')  
  # This should have 9 rows.
  # if for some reason there are not 9, need to decrease the number of colors specified below. 
  
  # Take the 4th through the last characters (exclude 'L1_') 
  # L1s$fullnodelabels <- substring(L1s$nodelabels, 4)
  
  # Make a reference table of the full node names and shorter node names.
  L1sref <- data.frame(nodelabels = L1s$nodelabels,
    # fullnodelabels=c("Milk_and_Milk_Products", "Meat_Poultry_Fish_and_Mixtures",             
    #                                     "Eggs",                   "Dry_Beans_Peas_Other_Legumes_Nuts_and_Seeds",
    #                                     "Grain_Product",          "Fruits", 
    #                                     "Vegetables",             "Fats_Oils_and_Salad_Dressings", 
    #                                     "Sugars_Sweets_and_Beverages"),
                       shortnodelabels=c("Milks",                  "Meats",
                                         "Eggs",                   "Legumes",
                                         "Grains",                 "Fruits", 
                                         "Vegetables",             "Fats", 
                                         "Sweets&\nBeverages"),
                       hilightcolors=  c('lightblue',              'firebrick1',        # Add 9 colors for highlighting each L1.
                                         'orange',                 'royalblue',
                                         'gold',                   'darkorchid',
                                         'seagreen',               'lightgreen',
                                         'rosybrown1'),
                       L1labelcolors=  c('lightblue4',             'firebrick',         # Add 9 colors for annotating each L1.
                                          'darkorange',            'darkblue',
                                          'gold4',                 'darkorchid',
                                          'seagreen',               'limegreen',
                                          'mediumvioletred'))

  L1sref
  
  # Merge the shortnodelabels to L1s
  merged1 <- merge(x=L1s, y=L1sref, all.x=T, by='nodelabels') # all.x=T ignores items in y that is missing in x. 
  
  # merge() sorts rows automatically, so need to re-sort it to the original order - by seqnum.
  # and sort the columns also so that nodelabels (column 1) and shortnodelabels (column 5) will be next to each other.
  L1s <- merged1[order(merged1$seqnum), c(1,5,2:4,6:7)]
  
  # Ensure the nodelabels and shortnodelabels are matching.
  L1s
  
  # Make vectors for plotting.
  L1nodenum       <- L1s$nodenum
  L1nodelabels    <- L1s$shortnodelabels
  L1hilightcolors <- L1s$hilightcolors
  L1labelcolors   <- L1s$L1labelcolors
  
  
  # highlight and annotate L1s using the nodenumbers. 
  tree_an_hi <- ggtree(tree, ladderize = F, layout = 'radial') +
    # geom_text(aes(label=node), hjust= -0.3) +
    geom_hilight(   node=L1nodenum[1],  fill=L1hilightcolors[1]) +  # Milk products
    geom_cladelabel(node=L1nodenum[1], color=  L1labelcolors[1], label=L1nodelabels[1], offset=0.5, geom="label", fill='white', hjust=0.5) + 
    geom_hilight(   node=L1nodenum[2],  fill=L1hilightcolors[2]) +  # Meat & fish
    geom_cladelabel(node=L1nodenum[2], color=  L1labelcolors[2], label=L1nodelabels[2], offset=0.5, geom="label", fill='white', hjust=0.5) + 
    geom_hilight(   node=L1nodenum[3],  fill=L1hilightcolors[3]) +  # Eggs
    geom_cladelabel(node=L1nodenum[3], color=  L1labelcolors[3], label=L1nodelabels[3], offset=0.5, geom="label", fill='white', hjust=0.5) +  
    geom_hilight(   node=L1nodenum[4],  fill=L1hilightcolors[4]) +  # Legumes, nuts & seeds
    geom_cladelabel(node=L1nodenum[4], color=  L1labelcolors[4], label=L1nodelabels[4], offset=0.5, geom="label", fill='white', hjust=0.5) + 
    geom_hilight(   node=L1nodenum[5],  fill=L1hilightcolors[5]) +  # Grain products
    geom_cladelabel(node=L1nodenum[5], color=  L1labelcolors[5], label=L1nodelabels[5], offset=0.5, geom="label", fill='white', hjust=0.5) + 
    geom_hilight(   node=L1nodenum[6],  fill=L1hilightcolors[6]) +  # Fruits
    geom_cladelabel(node=L1nodenum[6], color=  L1labelcolors[6], label=L1nodelabels[6], offset=0.5, geom="label", fill='white', hjust=0.5) +
    geom_hilight(   node=L1nodenum[7],  fill=L1hilightcolors[7]) +  # Vegetables
    geom_cladelabel(node=L1nodenum[7], color=  L1labelcolors[7], label=L1nodelabels[7], offset=0.5, geom="label", fill='white', hjust=0.5) + 
    geom_hilight(   node=L1nodenum[8],  fill=L1hilightcolors[8]) +  # Fats & oils
    geom_cladelabel(node=L1nodenum[8], color=  L1labelcolors[8], label=L1nodelabels[8], offset=0.5, geom="label", fill='white', hjust=0.5) + 
    geom_hilight(   node=L1nodenum[9],  fill=L1hilightcolors[9]) +  # Sweets & beverages
    geom_cladelabel(node=L1nodenum[9], color=  L1labelcolors[9], label=L1nodelabels[9], offset=0.5, geom="label", fill='white', hjust=0.5)   
  tree_an_hi
  
  # Widen the opening of the tree  
  tree_an_hi_o <- open_tree(tree_an_hi, 10)

  # Rotate the tree so that the root (break) will come to the bottom
  tree_an_hi_o_rt275 <- rotate_tree(tree_an_hi_o, 275) # 270 + 10*0.5 
  tree_an_hi_o_rt275

# Save the tree with the food names.
  ggsave("MCT_Lv4_ann_hili7x7_rt270_rd.tif", tree_an_hi_o_rt275, width=7, height=7, device='tiff', dpi=200)
  
# ---------------------------------------------------------------------------------------------------------------
  
 # Example
  set.seed(2017-02-16)
  tree <- rtree(50)
  ggtree(tree)
  
  treetext = "(((ADH2:0.1[&&NHX:S=human], ADH1:0.11[&&NHX:S=human]):
  0.05 [&&NHX:S=primates:D=Y:B=100],ADHY:
  0.1[&&NHX:S=nematode],ADHX:0.12 [&&NHX:S=insect]):
  0.1[&&NHX:S=metazoa:D=N],(ADH4:0.09[&&NHX:S=yeast],
  ADH3:0.13[&&NHX:S=yeast], ADH2:0.12[&&NHX:S=yeast],
  ADH1:0.11[&&NHX:S=yeast]):0.1[&&NHX:S=Fungi])[&&NHX:D=N];"
  
  tree <- read.tree(textConnection(treetext))

  ggtree(tree) + geom_tiplab() + 
    geom_label(aes(x=branch, label='S'), fill='lightgreen') + 
    geom_label(aes(label="D"), fill='steelblue') + 
    geom_text(aes(label='B'), hjust=-.5)
  

# ---------------------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------------
  
